# Generated by Django 5.0.7 on 2024-08-02 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('HOUSING', 'HOUSING'), ('FOOD', 'FOOD'), ('TRANSPORTATION', 'TRANSAPORTATION'), ('FAMILY', 'FAMILY'), ('HOUSING', 'HOUSING'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('period', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('ANNUALLY', 'ANNUALLY')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
