# Generated by Django 5.0.7 on 2024-07-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseaccount',
            name='account_type',
            field=models.CharField(default='savings', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='baseaccount',
            name='created_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
